const dummyText = `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices ante eget blandit dictum. Nunc augue lorem, fermentum eu vestibulum ut, maximus non libero. Duis tortor ante, vestibulum eu pretium pretium, viverra sit amet dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras et vehicula nulla. Sed scelerisque dolor a neque aliquet pharetra. Etiam non dictum risus. Donec quis lobortis massa. Pellentesque ac enim non augue tincidunt tempor. Pellentesque eu consectetur turpis. Suspendisse scelerisque laoreet tellus et vulputate. Phasellus semper turpis at pellentesque luctus. Nullam facilisis elit et varius tempus. Suspendisse bibendum porta lectus at ullamcorper. Donec felis odio, faucibus sed pharetra in, varius ullamcorper erat. Sed sit amet dictum est.
    Integer vestibulum rhoncus arcu pharetra fringilla. Quisque sapien nulla, lacinia a tristique at, tincidunt a turpis. Ut bibendum eleifend ante vitae accumsan. Maecenas malesuada nisl id luctus condimentum. Nunc ac molestie quam. Pellentesque tempor turpis lacus. Duis eu ligula eleifend nisl facilisis fermentum ut eget augue. Nam pellentesque urna ac mi efficitur, quis imperdiet ipsum cursus. Phasellus eu venenatis mi. Duis tempus non quam vel egestas. Proin iaculis cursus lectus id cursus. Curabitur quis purus sapien. Donec tincidunt interdum neque, sed molestie nisi faucibus sed. Nulla eu tristique enim, sed imperdiet mauris.
    Nunc dolor sapien, maximus eu justo quis, mollis cursus arcu. Phasellus finibus luctus eros, eget ultricies mauris volutpat vitae. Donec sit amet tristique erat, et sodales felis. Vivamus ullamcorper, odio id bibendum ornare, neque arcu dictum nisl, quis tristique ante mi et turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum convallis maximus augue, eget posuere libero lacinia ac. Integer auctor pharetra ultricies. Aenean quis dictum augue, nec aliquam nunc. Ut viverra, urna nec luctus convallis, mi justo laoreet dui, vel dictum metus ante vitae arcu. Proin aliquet suscipit elit non mollis. Fusce sit amet ultrices lectus.
    Maecenas et dui dictum, rhoncus lorem vel, accumsan dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dignissim elit nec libero dapibus, et vulputate velit imperdiet. Sed viverra massa at justo finibus ullamcorper. Aliquam lacinia rutrum placerat. Nulla id accumsan enim. Duis ac nulla dictum, dictum nulla eget, posuere ipsum. Ut tincidunt odio quis lacus cursus malesuada et ac turpis. Donec ultricies sapien blandit enim vulputate, eu tincidunt risus feugiat. Maecenas turpis sapien, tristique nec imperdiet at, luctus at lorem. Suspendisse pellentesque dignissim ultrices. Etiam finibus blandit erat eu elementum. Morbi auctor mauris sit amet urna sollicitudin luctus. Sed venenatis augue nec enim viverra malesuada.
    Phasellus elementum felis ut eleifend laoreet. Phasellus et venenatis odio. Nunc nec vehicula elit, eget accumsan nisi. Curabitur at sodales justo. Maecenas enim neque, blandit ut sollicitudin non, luctus dignissim massa. Sed nulla sem, tincidunt quis convallis ac, mollis vestibulum quam. Curabitur nec pharetra purus. Sed fermentum sapien quis sapien viverra, sed lobortis lacus euismod.
`;

export { dummyText };
